In [2]:
import numpy as np

In [6]:
a = np.array([2,3])
b = np.array([1,4])


In [7]:
a*4

array([ 8, 12])

In [8]:
a+b

array([3, 7])

In [9]:
b/2

array([0.5, 2. ])

In [10]:
np.cross(a,b)

array(5)

In [12]:
c = np.array([1,3])
d=np.array([4,1])
np.cross(c,d)

array(-11)

In [15]:
# Transpose
A = np.array([[1,3], [4,5]])
B = np.array([[3,4], [8,2]])

A.T

array([[1, 4],
       [3, 5]])

In [16]:
# determinate
np.linalg.det(A)

-6.999999999999999

In [17]:
#inverse 
np.linalg.inv(A)

array([[-0.71428571,  0.42857143],
       [ 0.57142857, -0.14285714]])