<a href="https://colab.research.google.com/github/chaudhary-dotcom/Python-Beginning-/blob/main/Numpy_Basics_24_11_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

print("Hello")

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
print(np.__version__)


1.26.4


In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
#0-D array
import numpy as np
arr=np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [ ]:
#1-D array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
#2-D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
#3-D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


In [ ]:
#Check number of dimension
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimension:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension: 5


In [ ]:
#Array Indexing
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
#Array Sum
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
#Access the element on the first row,second column
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element o first row: ',arr[0,1])

2nd element o first row:  2


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row: ',arr[1,4])

5th element on 2nd row:  10


In [ ]:
#3-D Arrays

import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])


6


In [ ]:
#negative indexing
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ',arr[1,-1])

Last element from 2nd dim:  10


In [ ]:
#Slicig
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])
print(arr)
print(type(arr))


[5 6 7]
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [ ]:
#Slice from the index 3 from the end to index 1 from the end
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [ ]:
#Step: Return every other element from idex 1 to index 5:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])


[[2 3 4]
 [7 8 9]]


In [ ]:
#Data type of an array
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
import numpy as np
arr=np.array(['apple','banana','cherry'])

print(arr.dtype)

<U6


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
#change the datatype from float to integer by using int as parameter value
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('int')
print(newarr)
print(newarr.dtype)
print(arr)
print(arr.dtype)

[1 2 3]
int64
[1.1 2.1 3.1]
float64


In [ ]:
#Change datatype from int to bool
import numpy as np
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
import numpy as np
array1=np.array([2,4,6],dtype='int32')
print(array1,array1.dtype)

[2 4 6] int32


In [ ]:
#Copy
import numpy as np
arr=np.array([1,2,3,4,5])
a = arr.copy()
arr[0]=42

print(a)
print(arr)


[1 2 3 4 5]
[42  2  3  4  5]


In [ ]:
#View
import numpy as np
arr = np.array([1,2,3,4,5])
a = arr.view()
c=arr.copy()
arr[3]=42
print(a)
print(arr)
print(c)


[ 1  2  3 42  5]
[ 1  2  3 42  5]
[1 2 3 4 5]


In [ ]:
#Make a view and chage the view
import numpy as np
arr=np.array([1,2,3,4,5])
a=arr.view()
a[0]=31
print(arr)
print(a)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
#Check array if its owns a data or not
import numpy as np
arr=np.array([1,2,3,4,5])
a=arr.copy()
b=arr.view()

print(a.base)
print(b.base)

None
[1 2 3 4 5]


In [ ]:
#Shape
#Print the shape of a 2D array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
#Array creating 5 dimension
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [ ]:
#Reshape from 1D to 2D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Reshape from 1D to 3D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#Returns copy or view
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
#Convert 1D array with 8 elements to 3D array with 2*2 elements
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Convert the array into a 1D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
#Iterating Arrays
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [ ]:
#Iterating 2D arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [ ]:
#Iterate on each scalar element of the 2D array:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for a in arr:
  for b in a:
    print(b)

1
2
3
4
5
6


In [ ]:
#Iterating 3D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for a in arr:
  for b in a:
    for c in b:
      print(c)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np
arr=np.array([1,2,3])
for a in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
  print(a)

b'1'
b'2'
b'3'


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for a in np.nditer(arr[:,::2]):
  print(a)

1
3
5
7


In [ ]:
import numpy as np
arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx,y in np.ndenumerate(arr):
  print(idx,y)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
#Joining Array
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
#Join 2-D arrays along rows
#Using Concatenate function
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Using Stacking function
#stack()
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Stacking along rows
#hstack()
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.hstack((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#Stacking along columns
#vstack()
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.vstack((arr1,arr2,arr3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Stacking along Height(depth)
#dstack()
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
#Splitting Arrays
#array_split()
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Split the array in 4 parts
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
#access the splitted arrays
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
#splitting 2D array into three
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#hsplit
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#Searching arrays
#where()
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
a=np.where(arr==4)
print(a)

(array([3, 5, 6]),)


In [ ]:
#finding even values
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
a=np.where(arr%2==0)
b=np.where(arr%2==1)
print(a)
print(b)

(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


In [ ]:
#searchsorted
import numpy as np
arr=np.array([6,7,8,9])
a=np.searchsorted(arr,7)
b=np.searchsorted(arr,9)
print(a)
print(b)



1
3


In [ ]:
#side='right'
import numpy as np
arr=np.array([6,7,8,9])
a=np.searchsorted(arr,7,side='right')
b=np.searchsorted(arr,6,side='right')
print(a)
print(b)

2
1


In [ ]:
#multiple values
import numpy as np
arr=np.array([1,3,5,7])
a=np.searchsorted(arr,[2,4,6])
print(a)

[1 2 3]


In [ ]:
#Sorting Arrays
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
#sort array alphabetically
import numpy as np
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
#sort boolen array
import numpy as np
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [ ]:
#Sorting 2D array
import numpy as np
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#Filter arrays
#If value at an index True=included
#If value False=excluded

import numpy as np
arr=np.array([41,42,43,44])
a=[True,False,True,False]
newarr=arr[a]
print(newarr)

[41 43]


In [ ]:
import numpy as np
arr=np.array([41,42,43,44])

#create an empty list
filter_arr=[]

#go through each element in arr
for element in arr:
  #if the element is higher than 42, set the value true, otherwise false:
  if element>42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])

#create an empty list
filter_arr=[]
for element in arr:
  if element%2==0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
#Creating filter directly
import numpy as np
arr=np.array([41,42,43,44])
filter_arr =arr>42

newarr=arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
filter_arr=arr%2==0

newarr=arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
